### ISSUE TITLE
Kritzkrieg: add defense buff to Medic while ubered

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/VSH-Rewrite-Configs#13]
Kritzkrieg is the only medigun that doesn't do anything to the medic while ubering, it's also the only medigun that allows rage stuns to go through its uber, so if you use its uber right, you'll most likely just get stunned (if the boss' rage can do so) then targeted. The defense buff would give you a slightly better chance of living, as other mediguns already do that pretty well.

(pull request can't be done as there's no self cond addition event, this was discussed with 42 and he said it wouldn't be too hard to add)

**Comment by UrUgli** [comment]
I don't want it to become an upgraded medi gun, so i think if the kritz was shortened and add an invincible  uber time that is also shorter it would be fine, as we have enough high damage stuff for me.

**Comment by FortyTwoFortyTwo** [comment]
Defense buff will likely only allow medic to survive 1 hit, unlike uber with unlimited hit so it probably fine for now.
