### ISSUE TITLE
Darwin's Danger Shield changes

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/VSH-Rewrite-Configs#2]
This weapon at the moment is almost never used, since it's basically razorback v2. I thought of this to make it better.

Darwin's Danger Shield:

-  -75% fall-damage
- No self-damage when wall-climbing

This changes will actually force pepole to aim better while having the climbing advantage without spamming the usual SMG.

**Comment by FortyTwoFortyTwo** [comment]
Can easily create tag for the fall damage, `damage_resistances_fall`

Creating tag for your self-damage when wall-climbing is slight more harder, as i would need to check every weapon slot before climb/melee slot, whenever to override or not. So i'll ignore 2nd suggestion for now

**Comment by UrUgli** [comment]
New attributes

- Remove the "No self-damage when wall-climbing"
- Higher normal jumps (like the scout's winger)
