### ISSUE TITLE
Gunboats changes

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/VSH-Rewrite-Configs#3]
Soldiers mostly use the banners in VSH, leaving the gunboats and mantreads almost never used.
Here is my suggestion

- -75% self-damage from your rockets
- Mini-crit when airborne
- -30% fall-damage

This will encourage a new playstyle for soldiers, and enjoy another way to play.

**Comment by FortyTwoFortyTwo** [comment]
Don't really want to add changes to self-damage from rocket when gunboats already have 60%, really just 15% extra.

Mini-crit when airborne would be hard to add as there no attribute for it, unless if i want to use full crit instead from market garnder, which is probably too much

Could just simply add -50% less fall damage, using tag `damage_resistances_fall`
