### ISSUE TITLE
Unusual Adachi skin still shows particles when invisible as Gentlespy.

### ISSUE THREAD

**Issue by Waifers** [redsunservers/VSH-Rewrite-Configs#34]
Expected interaction: When you have an Unusual Adachi skin equipped when you play Gentlespy, whenever you use the cloak, the unusual particles should go away until you become visible again.

Actual interaction: Unusual particles stay around Gentlespy whenever he cloaks, which gives away his position which should never be the case.

**Comment by FortyTwoFortyTwo** [comment]
Should've made issue in LoadoutBugTracker since this bug is not anywhere related to the configs/weapon balances itself.
Still going to leave issue open, unless you make new one there.

**Comment by Waifers** [comment]
reposted to loadoutbugtracker.
