### ISSUE TITLE
Mantreads changes

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/VSH-Rewrite-Configs#4]
Similar to the gunboat counterpart, these are still not used a lot, given you can stomp and do a huge load a damage, but a cost of having fall damage that will most likely lower your hp a lot.
Here's my suggestion

Mantreads:

- -75% self-damage from your rockets
- -30% fall damage
- Stomp damage reduced from 1008 to 500.

While having the same changes to the gunboats, it will make jumping on hale a bit less dangerous to your own HP. The reduced damage is normal as it would be too powerful given the changes.

**Comment by FortyTwoFortyTwo** [comment]
similar to comments i said about Gunboats, Mantreads would be near direct upgrade to gunboats unless if i don't add less self-damage or fall-damage. Which case i would add less self-damage and not fall-damage

**Comment by UrUgli** [comment]
New attributes:

- Remove "-30% fall damage" (When stomping hale, you take no fall damage anyways)
