### ISSUE TITLE
Soda Popper changes

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/VSH-Rewrite-Configs#5]
Right now the scout as a lot of viable primarys, but one of them is a bit too annoying for hale to fight against.
Here's my suggestion

Soda Popper :

- Hype meter builds less faster
- Reduce the jumps from 5 to 3 max
- Hype is disabled when 3 players are left (so it doesn't override the usual no double jump at 3)

It may be only nerfs, but the soda popper is really annoying as of now since he can make hale run for hours until he can even catch him.

**Comment by FortyTwoFortyTwo** [comment]
Can use `damage_event_scale` from baby face blaster for builds less faster.

Reducing jumps would be a lot more harder to do as those are not easy to detect/prevent it, but slower build is probably enough for it anyway.

**Comment by FortyTwoFortyTwo** [comment]
Done by wo in #20
