### ISSUE TITLE
Suggestion: add a tag that limits the amount of wall climbs a weapon can do until the player touches the ground

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/VSH-Rewrite-Configs#52]
Name can be `climb_max` as discussed, this would help with weapons that have a short climb height but can be spammed, while avoiding being able to reach massive heights (like Shiv used to). This could also replace cooldown entirely if default value is set to 1, fixing https://github.com/redsunservers/LoadoutBugTracker/issues/390 in the main Red Sun Bug Tracker as well.

**Comment by FortyTwoFortyTwo** [comment]
Added (https://github.com/redsunservers/VSH-Rewrite-Configs/commit/8a96bd93eb1ac4d1a4ed504be52a3d8c62a7e4b2)
