### ISSUE TITLE
Spy changes

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/VSH-Rewrite-Configs#6]
As of now, spy is known to do a huge load of damage, i want to suggest some changes to fix some points
Here's my suggestion

Spy :
- Hale becomes immune to backstabs during some time before becomming backstabable again (5 seconds should be enough)
- Backstabs do less damage over the number of time hale has been backstabbed.

This will prevent to completly destroy high winstreak hales (or even hale in general) as he can take too much damage while not being able to do anything.

**Comment by FortyTwoFortyTwo** [comment]
I'll wait until i get more info from logs on damages spy done in general comparing to other classes, seeing if it too much damage or not.

As for winstreak, it suppose to be hard to keep your winstreak while getting less and less health

**Comment by FortyTwoFortyTwo** [comment]
Totally not late to this
I've updated backstab damage to always deal 1000dmg, rather than 1500dmg most of the time, along with few boss hp changes.
I may also reduce damage on every backstabs done, but going to see how this goes first.
