### ISSUE TITLE
Tribalman's Shiv changes

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/VSH-Rewrite-Configs#7]
Sniper melees as of now have no advantages except that they all have the wall climb ability, i want to expand on that.
Here's my suggestion:

Tribalman's Shiv :

- Delay of wall-climb has been reduced from 3 seconds to 1 second
- Wall-climbing now does 30 damage instead of 15
- Missing hale or the wall deals bleed damage for 3 seconds.

This will make a change of melee playstyle for snipers, who will choose between which one they think is the best.

**Comment by FortyTwoFortyTwo** [comment]
Probably don't need too much downsides seeing how crit shiv + bleed deals less damage than crit stock
